import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Header } from "../components";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT_Dark_Responsive_Landing_Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header styles={styles} />
    </div>
  );
}
